/* DO NOT EDIT THIS FILE - it is machine generated */
#include <C:\Program Files\Java\jdk1.8.0_201\include\jni.h>
/* Header for class JNI */

#ifndef _Included_JNI
#define _Included_JNI
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     JNI
	 * Method:    multi01
	 * Signature: ([D[D)D
	 */
	JNIEXPORT jdouble JNICALL Java_JNI_multi01
	(JNIEnv *, jobject, jdoubleArray, jdoubleArray);

	/*
	 * Class:     JNI
	 * Method:    multi02
	 * Signature: ([D)D
	 */
	JNIEXPORT jdouble JNICALL Java_JNI_multi02
	(JNIEnv *, jobject, jdoubleArray);

	/*
	 * Class:     JNI
	 * Method:    multi03
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_JNI_multi03
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif